### YamlMime:Role 
title: Tecnico responsabile della sicurezza 
metadata: 
  title: Tecnico responsabile della sicurezza 
  description: I tecnici responsabili della sicurezza implementano controlli di sicurezza e la protezione contro le minacce, gestiscono le identità e l’accesso, proteggono i dati, le applicazioni e le reti. 
uid: role.security-engineer 
summary: | 
  I tecnici responsabili della sicurezza implementano controlli di sicurezza e la protezione contro le minacce, gestiscono le identità e l’accesso, proteggono i dati, le applicazioni e le reti.
subTitle: I tecnici responsabili della sicurezza implementano controlli di sicurezza e la protezione contro le minacce, gestiscono le identità e l’accesso, proteggono i dati, le applicazioni e le reti.
certificationPaths: 
- title: Azure Security Engineer
  linkedInKeywords: Azure Security Engineer
  uid: certification-path.azure-security-engineer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-security-engineer
    levels:
    - intermediate
- title: Identity and Access Administrator
  linkedInKeywords: Identity and Access Administrator
  uid: certification-path.identity-and-access-administrator
  prerequisites: 
  - uid: certification.security-compliance-and-identity-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.identity-and-access-administrator
    levels:
    - intermediate
- title: Information Protection Administrator
  linkedInKeywords: Information Protection Administrator
  uid: certification-path.information-protection-administrator
  prerequisites: 
  - uid: certification.security-compliance-and-identity-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.information-protection-administrator
    levels:
    - intermediate
- title: Security Operations Analyst
  linkedInKeywords: Security Operations Analyst
  uid: certification-path.security-operations-analyst
  prerequisites: 
  - uid: certification.security-compliance-and-identity-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.security-operations-analyst
    levels:
    - intermediate
certifications:
- uid: certification.azure-security-engineer
  requiredExams:
  - uid: exam.az-500
- uid: certification.security-operations-analyst
  requiredExams:
  - uid: exam.sc-200
- uid: certification.identity-and-access-administrator
  requiredExams:
  - uid: exam.sc-300
- uid: certification.information-protection-administrator
  requiredExams:
  - uid: exam.sc-400
resources:
- title: Guida alla formazione e alle certificazioni Microsoft
  description: Esplora tutte le certificazioni in questa guida sintetica alla formazione e alla certificazione.
  href: https://aka.ms/TrainingCertDeck
- title: Poster sulla formazione e sulle certificazioni
  description: Usa il poster sulla formazione e sulle certificazioni per scegliere il percorso da seguire per raggiungere il successo.
  href: https://aka.ms/traincertposter
- title: Assistenza per le certificazioni
  href: ../help.md
  description: Ottieni assistenza tramite i forum di supporto per la certificazione Microsoft. Un moderatore del forum ti risponderà entro un giorno lavorativo, dal lunedì al venerdì.
