### YamlMime:Role 
title: Architetto di soluzioni 
metadata: 
  title: Architetto di soluzioni 
  description: Gli architetti di soluzioni sono esperti in materia di elaborazione, rete, archiviazione e sicurezza.
uid: role.solution-architect  
summary: | 
  Gli architetti di soluzioni sono esperti in materia di elaborazione, rete, archiviazione e sicurezza.
subTitle: Gli architetti di soluzioni sono esperti in materia di elaborazione, rete, archiviazione e sicurezza.
certificationPaths: 
- title: Azure Solutions Architect
  linkedInKeywords: Azure Solutions Architect
  uid: certification-path.azure-solutions-architect 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-solutions-architect
    levels:
    - advanced    
- title: Dynamics 365 Finance and Operations Apps Solution Architect
  linkedInKeywords: Dynamics 365 Finance and Operations Apps Solution Architect
  uid: certification.d365-finance-and-operations-apps-solution-architect-expert
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate  
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate 
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate 
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate 
  - uid: certification.d365-finance-and-operations-apps-solution-architect-expert
    levels:
    - advanced  
- title: Power Apps + Dynamics 365 Solution Architect
  linkedInKeywords: Power Apps + Dynamics 365 Solution Architect
  uid: certification.power-apps-and-d365-solution-architect-expert
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-apps-and-d365-developer-associate
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate
    - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate
  - uid: certification.power-apps-and-d365-solution-architect-expert
    levels:
    - advanced
certifications:
- uid: certification.azure-solutions-architect
  requiredExams:
  - uid: exam.az-300
  - uid: exam.az-301
- uid: certification.d365-finance-and-operations-apps-solution-architect-expert
  requiredExams:
  - uid: exam.mb-700
- uid: certification.power-apps-and-d365-solution-architect-expert
  requiredExams:
  - uid: exam.mb-600
resources:
- title: Guida alla formazione e alle certificazioni Microsoft
  description: Esplora tutte le certificazioni in questa guida sintetica alla formazione e alla certificazione.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Poster sulla formazione e sulle certificazioni
  description: Usa il poster sulla formazione e sulle certificazioni per scegliere il percorso da seguire per raggiungere il successo.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Assistenza per le certificazioni
  href: ../help.md
  description: Ottieni assistenza tramite i forum di supporto per la certificazione Microsoft. Un moderatore del forum ti risponderà entro un giorno lavorativo, dal lunedì al venerdì.

