### YamlMime:Certification
title: 'MTA: HTML5 Application Development Fundamentals'
metadata:
  title: 'MTA: HTML5 Application Development Fundamentals'
  description: 'MTA: HTML5 Application Development Fundamentals'
uid: certification.mta-html5-application-development-fundamentals
iconUrl: /media/learn/certification/badges/mta-badge.svg
summary: |-
  <div><font color='red'><strong>In risposta alla situazione del Coronavirus (COVID-19), Microsoft sta implementando diverse modifiche temporanee al suo programma di formazione e certificazione. <a href='https://www.microsoft.com/en-us/learning/community-blog-post.aspx?BlogId=8&amp;Id=375289'>Ulteriori informazioni</a>.</strong></font><br/><br/></div>
  
  Le certificazioni MTA sono un ottimo punto di partenza se vuoi entrare nel campo della tecnologia. Le certificazioni MTA riguardano un'ampia gamma di concetti tecnici fondamentali, valutano e convalidano le conoscenze tecniche di base e migliorano la credibilità tecnica. Nota&#58; Gli esami MTA non sono validi per la certificazione MCP e non sono un prerequisito per la certificazione MCSA o MCSD.
subTitle: "Le certificazioni MTA sono un ottimo punto di partenza se vuoi entrare nel campo della tecnologia. Le certificazioni MTA riguardano un'ampia gamma di concetti tecnici fondamentali, valutano e convalidano le conoscenze tecniche di base e migliorano la credibilità tecnica. Nota: Gli esami MTA non sono validi per la certificazione MCP e non sono un prerequisito per la certificazione MCSA o MCSD."
levels:
- beginner
skills:
- nessuna
roles:
- developer
type: mta
products:
- vs
courses:
- uid: course.40375
- uid: course.40034
exams:
- uid: exam.98-375
resources:
- title: Guida alla formazione e alla certificazione
  description: Esplora tutte le certificazioni in questa guida sintetica alla formazione e alla certificazione.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Poster di certificazione
  description: Consulta la panoramica delle certificazioni di base, basate sui ruoli e di specializzazione.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Exam Replay
  description: Scopri due grandi offerte che ti aiutano a migliorare le tue probabilità di successo.
  href: deals.md
- title: Assistenza per le certificazioni
  description: Ottieni assistenza tramite i forum di supporto per la Microsoft Certification. Un moderatore del forum ti risponderà entro un giorno lavorativo, dal lunedì al venerdì.
  href: help.md
- title: Dashboard delle certificazioni
  description: Rivedi e gestisci gli appuntamenti programmati, i certificati e le trascrizioni.
  href: https://www.microsoft.com/learning/dashboard.aspx